# Generated by Django 4.0.6 on 2022-07-07 10:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CI')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
                ('copyright', models.CharField(max_length=150, verbose_name='copyright')),
                ('link_facebook', models.URLField(blank=True)),
                ('link_instagram', models.URLField(blank=True)),
                ('link_twitter', models.URLField(blank=True)),
                ('link_youtube', models.URLField(blank=True)),
                ('link_pinterest', models.URLField(blank=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
