# Generated by Django 4.0.6 on 2022-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_promotion'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
