# Generated by Django 4.0.6 on 2022-07-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_photo',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='second_photo',
            field=models.ImageField(default='2', upload_to=''),
            preserve_default=False,
        ),
    ]
