# Generated by Django 4.0.6 on 2022-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_first_photo_product_second_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
    ]
