# Generated by Django 4.0.6 on 2022-07-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsold',
            name='description',
        ),
        migrations.RemoveField(
            model_name='globalsold',
            name='promotion_percentage',
        ),
        migrations.RemoveField(
            model_name='globalsold',
            name='promotion_price',
        ),
        migrations.AlterField(
            model_name='globalsold',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
