# Generated by Django 4.0.6 on 2022-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_order_delete_orderitem_cart_order_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
