# Generated by Django 4.0.6 on 2022-08-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_order_color_order_color_remove_order_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
