# Generated by Django 4.0.6 on 2022-08-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_color_alter_product_size_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categories',
            new_name='category',
        ),
    ]
