# Generated by Django 4.0.6 on 2022-08-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_categories_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='shop.subcategory'),
            preserve_default=False,
        ),
    ]
