# Generated by Django 4.0.6 on 2022-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
